version: "3"

services:
  envoy-proxy:
    image: envoyproxy/envoy:v1.15.0
    ports:
      - 8081:51051
    volumes:
      - ./protos/proto.pb:/data/proto.pb
      - ./envoy-proxy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - grpc_app
    environment:
      - GRPC_VERBOSITY=debug

  grpc_app:
    build:
      dockerfile: Dockerfile.app
      context: .
    volumes:
      - .:/app/src/server
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongodb://mongo:27017
      - GRPC_VERBOSITY=debug

  grpc_gateway:
    build:
      dockerfile: Dockerfile.gateway
      context: .
    volumes:
      - ./gateway:/app/src/gateway
    depends_on:
      - grpc_app
    ports:
      - 8080:8080
    environment:
      - GRPC_VERBOSITY=debug
      - ENTITY_SERVER_HOST=grpc_app:50051

  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db

volumes:
  mongo:
