version: "3"

services:
  envoy-proxy:
    container_name: envoy-proxy
    image: envoyproxy/envoy:v1.15.0
    ports:
      - 8081:51051
    volumes:
      - ./protos/proto.pb:/data/proto.pb
      - ./envoy-proxy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - grpc_app

  grpc_app:
    container_name: grpc-app
    build:
      dockerfile: Dockerfile.app
      context: .
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongodb://mongo:27017

  denny:
    container_name: denny
    build:
      dockerfile: Dockerfile.denny
      context: .
    depends_on:
      - mongo
    ports:
      - 8082:8080
    environment:
      - DB_HOST=mongodb://mongo:27017
      # - GIN_MODE=release # Use this for production environment

  grpc_gateway:
    container_name: grpc-gateway
    build:
      dockerfile: Dockerfile.gateway
      context: .
    volumes:
      - ./gateway:/app/src/gateway
    depends_on:
      - grpc_app
    ports:
      - 8080:8080
    environment:
      - GRPC_VERBOSITY=debug
      - ENTITY_SERVER_HOST=grpc_app:50051

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo:/data/db

volumes:
  mongo:
