// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity/entity.proto

package entity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Entity message type for responding
type Entity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{0}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entity) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// Defintion of request and respone for each services
type CreateEntityReq struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityReq) Reset()         { *m = CreateEntityReq{} }
func (m *CreateEntityReq) String() string { return proto.CompactTextString(m) }
func (*CreateEntityReq) ProtoMessage()    {}
func (*CreateEntityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{1}
}

func (m *CreateEntityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityReq.Unmarshal(m, b)
}
func (m *CreateEntityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityReq.Marshal(b, m, deterministic)
}
func (m *CreateEntityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityReq.Merge(m, src)
}
func (m *CreateEntityReq) XXX_Size() int {
	return xxx_messageInfo_CreateEntityReq.Size(m)
}
func (m *CreateEntityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityReq proto.InternalMessageInfo

func (m *CreateEntityReq) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type CreateEntityRes struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityRes) Reset()         { *m = CreateEntityRes{} }
func (m *CreateEntityRes) String() string { return proto.CompactTextString(m) }
func (*CreateEntityRes) ProtoMessage()    {}
func (*CreateEntityRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{2}
}

func (m *CreateEntityRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityRes.Unmarshal(m, b)
}
func (m *CreateEntityRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityRes.Marshal(b, m, deterministic)
}
func (m *CreateEntityRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityRes.Merge(m, src)
}
func (m *CreateEntityRes) XXX_Size() int {
	return xxx_messageInfo_CreateEntityRes.Size(m)
}
func (m *CreateEntityRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityRes proto.InternalMessageInfo

func (m *CreateEntityRes) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type UpdateEntityReq struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEntityReq) Reset()         { *m = UpdateEntityReq{} }
func (m *UpdateEntityReq) String() string { return proto.CompactTextString(m) }
func (*UpdateEntityReq) ProtoMessage()    {}
func (*UpdateEntityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{3}
}

func (m *UpdateEntityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEntityReq.Unmarshal(m, b)
}
func (m *UpdateEntityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEntityReq.Marshal(b, m, deterministic)
}
func (m *UpdateEntityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEntityReq.Merge(m, src)
}
func (m *UpdateEntityReq) XXX_Size() int {
	return xxx_messageInfo_UpdateEntityReq.Size(m)
}
func (m *UpdateEntityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEntityReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEntityReq proto.InternalMessageInfo

func (m *UpdateEntityReq) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type UpdateEntityRes struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEntityRes) Reset()         { *m = UpdateEntityRes{} }
func (m *UpdateEntityRes) String() string { return proto.CompactTextString(m) }
func (*UpdateEntityRes) ProtoMessage()    {}
func (*UpdateEntityRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{4}
}

func (m *UpdateEntityRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEntityRes.Unmarshal(m, b)
}
func (m *UpdateEntityRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEntityRes.Marshal(b, m, deterministic)
}
func (m *UpdateEntityRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEntityRes.Merge(m, src)
}
func (m *UpdateEntityRes) XXX_Size() int {
	return xxx_messageInfo_UpdateEntityRes.Size(m)
}
func (m *UpdateEntityRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEntityRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEntityRes proto.InternalMessageInfo

func (m *UpdateEntityRes) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type ReadEntityReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadEntityReq) Reset()         { *m = ReadEntityReq{} }
func (m *ReadEntityReq) String() string { return proto.CompactTextString(m) }
func (*ReadEntityReq) ProtoMessage()    {}
func (*ReadEntityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{5}
}

func (m *ReadEntityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEntityReq.Unmarshal(m, b)
}
func (m *ReadEntityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEntityReq.Marshal(b, m, deterministic)
}
func (m *ReadEntityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEntityReq.Merge(m, src)
}
func (m *ReadEntityReq) XXX_Size() int {
	return xxx_messageInfo_ReadEntityReq.Size(m)
}
func (m *ReadEntityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEntityReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEntityReq proto.InternalMessageInfo

func (m *ReadEntityReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadEntityRes struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadEntityRes) Reset()         { *m = ReadEntityRes{} }
func (m *ReadEntityRes) String() string { return proto.CompactTextString(m) }
func (*ReadEntityRes) ProtoMessage()    {}
func (*ReadEntityRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{6}
}

func (m *ReadEntityRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEntityRes.Unmarshal(m, b)
}
func (m *ReadEntityRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEntityRes.Marshal(b, m, deterministic)
}
func (m *ReadEntityRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEntityRes.Merge(m, src)
}
func (m *ReadEntityRes) XXX_Size() int {
	return xxx_messageInfo_ReadEntityRes.Size(m)
}
func (m *ReadEntityRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEntityRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEntityRes proto.InternalMessageInfo

func (m *ReadEntityRes) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type DeleteEntityReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityReq) Reset()         { *m = DeleteEntityReq{} }
func (m *DeleteEntityReq) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityReq) ProtoMessage()    {}
func (*DeleteEntityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{7}
}

func (m *DeleteEntityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityReq.Unmarshal(m, b)
}
func (m *DeleteEntityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityReq.Marshal(b, m, deterministic)
}
func (m *DeleteEntityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityReq.Merge(m, src)
}
func (m *DeleteEntityReq) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityReq.Size(m)
}
func (m *DeleteEntityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityReq proto.InternalMessageInfo

func (m *DeleteEntityReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteEntityRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEntityRes) Reset()         { *m = DeleteEntityRes{} }
func (m *DeleteEntityRes) String() string { return proto.CompactTextString(m) }
func (*DeleteEntityRes) ProtoMessage()    {}
func (*DeleteEntityRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{8}
}

func (m *DeleteEntityRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEntityRes.Unmarshal(m, b)
}
func (m *DeleteEntityRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEntityRes.Marshal(b, m, deterministic)
}
func (m *DeleteEntityRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEntityRes.Merge(m, src)
}
func (m *DeleteEntityRes) XXX_Size() int {
	return xxx_messageInfo_DeleteEntityRes.Size(m)
}
func (m *DeleteEntityRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEntityRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEntityRes proto.InternalMessageInfo

func (m *DeleteEntityRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListEntitiesReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEntitiesReq) Reset()         { *m = ListEntitiesReq{} }
func (m *ListEntitiesReq) String() string { return proto.CompactTextString(m) }
func (*ListEntitiesReq) ProtoMessage()    {}
func (*ListEntitiesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{9}
}

func (m *ListEntitiesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEntitiesReq.Unmarshal(m, b)
}
func (m *ListEntitiesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEntitiesReq.Marshal(b, m, deterministic)
}
func (m *ListEntitiesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEntitiesReq.Merge(m, src)
}
func (m *ListEntitiesReq) XXX_Size() int {
	return xxx_messageInfo_ListEntitiesReq.Size(m)
}
func (m *ListEntitiesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEntitiesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListEntitiesReq proto.InternalMessageInfo

type ListEntitiesRes struct {
	Entity               *Entity  `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEntitiesRes) Reset()         { *m = ListEntitiesRes{} }
func (m *ListEntitiesRes) String() string { return proto.CompactTextString(m) }
func (*ListEntitiesRes) ProtoMessage()    {}
func (*ListEntitiesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b38ccb06a827056, []int{10}
}

func (m *ListEntitiesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEntitiesRes.Unmarshal(m, b)
}
func (m *ListEntitiesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEntitiesRes.Marshal(b, m, deterministic)
}
func (m *ListEntitiesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEntitiesRes.Merge(m, src)
}
func (m *ListEntitiesRes) XXX_Size() int {
	return xxx_messageInfo_ListEntitiesRes.Size(m)
}
func (m *ListEntitiesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEntitiesRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListEntitiesRes proto.InternalMessageInfo

func (m *ListEntitiesRes) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "entity.Entity")
	proto.RegisterType((*CreateEntityReq)(nil), "entity.CreateEntityReq")
	proto.RegisterType((*CreateEntityRes)(nil), "entity.CreateEntityRes")
	proto.RegisterType((*UpdateEntityReq)(nil), "entity.UpdateEntityReq")
	proto.RegisterType((*UpdateEntityRes)(nil), "entity.UpdateEntityRes")
	proto.RegisterType((*ReadEntityReq)(nil), "entity.ReadEntityReq")
	proto.RegisterType((*ReadEntityRes)(nil), "entity.ReadEntityRes")
	proto.RegisterType((*DeleteEntityReq)(nil), "entity.DeleteEntityReq")
	proto.RegisterType((*DeleteEntityRes)(nil), "entity.DeleteEntityRes")
	proto.RegisterType((*ListEntitiesReq)(nil), "entity.ListEntitiesReq")
	proto.RegisterType((*ListEntitiesRes)(nil), "entity.ListEntitiesRes")
}

func init() { proto.RegisterFile("entity/entity.proto", fileDescriptor_9b38ccb06a827056) }

var fileDescriptor_9b38ccb06a827056 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0xa5, 0x69, 0xe9, 0x7b, 0xbd, 0xfd, 0xbe, 0xe5, 0xbd, 0x97, 0x17, 0x04, 0xeb, 0x2c, 0x44,
	0x14, 0x1a, 0xa9, 0x0b, 0xd1, 0xad, 0xba, 0x73, 0x15, 0x29, 0x08, 0x6e, 0x8c, 0xc9, 0xa5, 0x0c,
	0xd4, 0x24, 0xcd, 0xa4, 0x82, 0x88, 0x1b, 0xff, 0x82, 0xff, 0xcb, 0x8d, 0x7f, 0xc1, 0x1f, 0x22,
	0x99, 0xa4, 0x4d, 0x32, 0x36, 0x50, 0x5d, 0x65, 0xe6, 0x9e, 0x73, 0xcf, 0x3d, 0x33, 0x67, 0x08,
	0x0c, 0xc8, 0x8b, 0x78, 0xf4, 0x68, 0x26, 0x9f, 0x51, 0x10, 0xfa, 0x91, 0x8f, 0xf5, 0x64, 0x67,
	0x6c, 0x4d, 0x7d, 0x7f, 0x3a, 0x23, 0xd3, 0x0e, 0xb8, 0x69, 0x7b, 0x9e, 0x1f, 0xd9, 0x11, 0xf7,
	0x3d, 0x91, 0xb0, 0xd8, 0x2d, 0xd4, 0x2f, 0x24, 0x0f, 0x3b, 0xa0, 0x71, 0x57, 0xaf, 0x0c, 0x2b,
	0x7b, 0x0d, 0x4b, 0xe3, 0x2e, 0x22, 0xd4, 0x3c, 0xfb, 0x9e, 0x74, 0x4d, 0x56, 0xe4, 0x1a, 0x87,
	0xd0, 0x74, 0x49, 0x38, 0x21, 0x0f, 0x62, 0x0d, 0xbd, 0x2a, 0xa1, 0x7c, 0x09, 0x7b, 0x50, 0x5d,
	0x84, 0x33, 0xbd, 0x26, 0x91, 0x78, 0xc9, 0x4e, 0xa0, 0x7b, 0x16, 0x92, 0x1d, 0x51, 0x32, 0xc7,
	0xa2, 0x39, 0xee, 0x42, 0x6a, 0x4e, 0x8e, 0x6b, 0x8e, 0x3b, 0xa3, 0xd4, 0x79, 0x4a, 0x49, 0xd1,
	0xaf, 0xad, 0xe2, 0x3b, 0xad, 0x93, 0xc0, 0xfd, 0xe9, 0xd4, 0x62, 0xeb, 0xe6, 0x53, 0xb7, 0xa1,
	0x6d, 0x91, 0xed, 0x66, 0x33, 0x95, 0x4b, 0x65, 0xc7, 0x45, 0xc2, 0xe6, 0xca, 0x3b, 0xd0, 0x3d,
	0xa7, 0x19, 0xe5, 0xcf, 0xa3, 0x6a, 0x1f, 0xa8, 0x14, 0x81, 0x3a, 0xfc, 0x12, 0x0b, 0xc7, 0x21,
	0x21, 0x24, 0xef, 0xb7, 0xb5, 0xdc, 0xb2, 0x3e, 0x74, 0x2f, 0xb9, 0x88, 0x24, 0x95, 0x93, 0xb0,
	0x68, 0x1e, 0x9f, 0xbb, 0x58, 0xda, 0xd8, 0xdd, 0xf8, 0xad, 0x0a, 0xed, 0xa4, 0x74, 0x45, 0xe1,
	0x03, 0x77, 0x08, 0x6f, 0xa0, 0x95, 0x8f, 0x0e, 0xff, 0x2d, 0x3b, 0x95, 0xb7, 0x60, 0x94, 0x00,
	0x82, 0xfd, 0x7f, 0x79, 0xff, 0x78, 0xd5, 0x06, 0xac, 0x91, 0x3c, 0x6b, 0x4e, 0xe2, 0x34, 0x1d,
	0x87, 0x16, 0x40, 0x76, 0x8b, 0xf8, 0x67, 0xa9, 0x50, 0xb8, 0x7a, 0x63, 0x6d, 0x59, 0xb0, 0xbf,
	0x52, 0xb6, 0x87, 0x9d, 0x95, 0xac, 0xf9, 0xc4, 0xdd, 0xe7, 0xd8, 0x70, 0x3e, 0xf5, 0xcc, 0xb0,
	0xf2, 0x8c, 0x8c, 0x12, 0x60, 0x65, 0xd8, 0x58, 0x63, 0xf8, 0x1a, 0x5a, 0xf9, 0x68, 0x32, 0x71,
	0x25, 0x53, 0xa3, 0x04, 0x58, 0xd9, 0xde, 0x57, 0x6d, 0x4f, 0xa0, 0x95, 0x0f, 0x2d, 0x53, 0x56,
	0xd2, 0x35, 0x4a, 0x00, 0xc1, 0xfa, 0x52, 0xb9, 0x89, 0x99, 0xed, 0xc3, 0xca, 0x5d, 0x5d, 0xfe,
	0x1d, 0x8e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x5d, 0xe2, 0xf3, 0x5a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EntityServiceClient is the client API for EntityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntityServiceClient interface {
	CreateEntity(ctx context.Context, in *CreateEntityReq, opts ...grpc.CallOption) (*CreateEntityRes, error)
	ReadEntity(ctx context.Context, in *ReadEntityReq, opts ...grpc.CallOption) (*ReadEntityRes, error)
	UpdateEntity(ctx context.Context, in *UpdateEntityReq, opts ...grpc.CallOption) (*UpdateEntityRes, error)
	DeleteEntity(ctx context.Context, in *DeleteEntityReq, opts ...grpc.CallOption) (*DeleteEntityRes, error)
	ListEntities(ctx context.Context, in *ListEntitiesReq, opts ...grpc.CallOption) (EntityService_ListEntitiesClient, error)
}

type entityServiceClient struct {
	cc *grpc.ClientConn
}

func NewEntityServiceClient(cc *grpc.ClientConn) EntityServiceClient {
	return &entityServiceClient{cc}
}

func (c *entityServiceClient) CreateEntity(ctx context.Context, in *CreateEntityReq, opts ...grpc.CallOption) (*CreateEntityRes, error) {
	out := new(CreateEntityRes)
	err := c.cc.Invoke(ctx, "/entity.EntityService/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) ReadEntity(ctx context.Context, in *ReadEntityReq, opts ...grpc.CallOption) (*ReadEntityRes, error) {
	out := new(ReadEntityRes)
	err := c.cc.Invoke(ctx, "/entity.EntityService/ReadEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) UpdateEntity(ctx context.Context, in *UpdateEntityReq, opts ...grpc.CallOption) (*UpdateEntityRes, error) {
	out := new(UpdateEntityRes)
	err := c.cc.Invoke(ctx, "/entity.EntityService/UpdateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) DeleteEntity(ctx context.Context, in *DeleteEntityReq, opts ...grpc.CallOption) (*DeleteEntityRes, error) {
	out := new(DeleteEntityRes)
	err := c.cc.Invoke(ctx, "/entity.EntityService/DeleteEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) ListEntities(ctx context.Context, in *ListEntitiesReq, opts ...grpc.CallOption) (EntityService_ListEntitiesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EntityService_serviceDesc.Streams[0], "/entity.EntityService/ListEntities", opts...)
	if err != nil {
		return nil, err
	}
	x := &entityServiceListEntitiesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EntityService_ListEntitiesClient interface {
	Recv() (*ListEntitiesRes, error)
	grpc.ClientStream
}

type entityServiceListEntitiesClient struct {
	grpc.ClientStream
}

func (x *entityServiceListEntitiesClient) Recv() (*ListEntitiesRes, error) {
	m := new(ListEntitiesRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EntityServiceServer is the server API for EntityService service.
type EntityServiceServer interface {
	CreateEntity(context.Context, *CreateEntityReq) (*CreateEntityRes, error)
	ReadEntity(context.Context, *ReadEntityReq) (*ReadEntityRes, error)
	UpdateEntity(context.Context, *UpdateEntityReq) (*UpdateEntityRes, error)
	DeleteEntity(context.Context, *DeleteEntityReq) (*DeleteEntityRes, error)
	ListEntities(*ListEntitiesReq, EntityService_ListEntitiesServer) error
}

// UnimplementedEntityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEntityServiceServer struct {
}

func (*UnimplementedEntityServiceServer) CreateEntity(ctx context.Context, req *CreateEntityReq) (*CreateEntityRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (*UnimplementedEntityServiceServer) ReadEntity(ctx context.Context, req *ReadEntityReq) (*ReadEntityRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEntity not implemented")
}
func (*UnimplementedEntityServiceServer) UpdateEntity(ctx context.Context, req *UpdateEntityReq) (*UpdateEntityRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEntity not implemented")
}
func (*UnimplementedEntityServiceServer) DeleteEntity(ctx context.Context, req *DeleteEntityReq) (*DeleteEntityRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEntity not implemented")
}
func (*UnimplementedEntityServiceServer) ListEntities(req *ListEntitiesReq, srv EntityService_ListEntitiesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEntities not implemented")
}

func RegisterEntityServiceServer(s *grpc.Server, srv EntityServiceServer) {
	s.RegisterService(&_EntityService_serviceDesc, srv)
}

func _EntityService_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entity.EntityService/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).CreateEntity(ctx, req.(*CreateEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_ReadEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).ReadEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entity.EntityService/ReadEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).ReadEntity(ctx, req.(*ReadEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_UpdateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).UpdateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entity.EntityService/UpdateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).UpdateEntity(ctx, req.(*UpdateEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_DeleteEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).DeleteEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entity.EntityService/DeleteEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).DeleteEntity(ctx, req.(*DeleteEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_ListEntities_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEntitiesReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntityServiceServer).ListEntities(m, &entityServiceListEntitiesServer{stream})
}

type EntityService_ListEntitiesServer interface {
	Send(*ListEntitiesRes) error
	grpc.ServerStream
}

type entityServiceListEntitiesServer struct {
	grpc.ServerStream
}

func (x *entityServiceListEntitiesServer) Send(m *ListEntitiesRes) error {
	return x.ServerStream.SendMsg(m)
}

var _EntityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entity.EntityService",
	HandlerType: (*EntityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _EntityService_CreateEntity_Handler,
		},
		{
			MethodName: "ReadEntity",
			Handler:    _EntityService_ReadEntity_Handler,
		},
		{
			MethodName: "UpdateEntity",
			Handler:    _EntityService_UpdateEntity_Handler,
		},
		{
			MethodName: "DeleteEntity",
			Handler:    _EntityService_DeleteEntity_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEntities",
			Handler:       _EntityService_ListEntities_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "entity/entity.proto",
}
